is_sequence: false
sample_count: 51088
sequence_size: -1
output_dim: 30
matrix_spec {
  col_count: 1
  row_count: 1
  num_channels: 1
  is_sequence_col: false
  is_sequence_row: false
  has_locality_col: true
  has_locality_row: true
  format: DENSE
}
label_to_index_map {
  key: 'yes'
  value: 0
}
label_to_index_map {
  key: 'no'
  value: 1
}
label_to_index_map {
  key: 'up'
  value: 2
}
label_to_index_map {
  key: 'down'
  value: 3
}
label_to_index_map {
  key: 'left'
  value: 4
}
label_to_index_map {
  key: 'right'
  value: 5
}
label_to_index_map {
  key: 'on'
  value: 6
}
label_to_index_map {
  key: 'off'
  value: 7
}
label_to_index_map {
  key: 'stop'
  value: 8
}
label_to_index_map {
  key: 'go'
  value: 9
}
label_to_index_map {
  key: 'zero'
  value: 10
}
label_to_index_map {
  key: 'one'
  value: 11
}
label_to_index_map {
  key: 'two'
  value: 12
}
label_to_index_map {
  key: 'three'
  value: 13
}
label_to_index_map {
  key: 'four'
  value: 14
}
label_to_index_map {
  key: 'five'
  value: 15
}
label_to_index_map {
  key: 'six'
  value: 16
}
label_to_index_map {
  key: 'seven'
  value: 17
}
label_to_index_map {
  key: 'eight'
  value: 18
}
label_to_index_map {
  key: 'nine'
  value: 19
}
label_to_index_map {
  key: 'bed'
  value: 20
}
label_to_index_map {
  key: 'bird'
  value: 21
}
label_to_index_map {
  key: 'cat'
  value: 22
}
label_to_index_map {
  key: 'dog'
  value: 23
}
label_to_index_map {
  key: 'happy'
  value: 24
}
label_to_index_map {
  key: 'house'
  value: 25
}
label_to_index_map {
  key: 'marvin'
  value: 26
}
label_to_index_map {
  key: 'sheila'
  value: 27
}
label_to_index_map {
  key: 'tree'
  value: 28
}
label_to_index_map {
  key: 'wow'
  value: 29
}

